/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    WatermarkCropper: typeof import('./src/components/WatermarkCropper.vue')['default']
  }
}
