pub use generate_background::generate_background;
pub use get_background_dir_abs_path::get_background_dir_abs_path;
pub use get_background_dir_relative_path::get_background_dir_relative_path;
pub use get_config::get_config;
pub use get_jpg_image_infos::get_jpg_image_infos;
pub use get_manga_dir_data::get_manga_dir_data;
pub use open_image::open_image;
pub use remove_watermark::remove_watermark;
pub use save_config::save_config;
pub use show_path_in_file_manager::show_path_in_file_manager;
pub use  search_manga::search_manga;
pub use get_manga_data::get_manga_data;

mod generate_background;
mod get_background_dir_abs_path;
mod get_background_dir_relative_path;
mod get_config;
mod get_jpg_image_infos;
mod get_manga_dir_data;
mod open_image;
mod remove_watermark;
mod save_config;
mod show_path_in_file_manager;
mod search_manga;
mod get_manga_data;
